-
  uriPattern: 'neos/api/deepl/translate'
  defaults:
    '@controller': 'Api\Translate'
    '@package': 'SteinbauerIT.Neos.DeepLNodeTranslate'
    '@action': 'translate'
    '@format': 'json'

-
  uriPattern: 'neos/api/deepl/translatenodeandtheirchildrenbyidentifier'
  defaults:
    '@controller': 'Api\Translate'
    '@package': 'SteinbauerIT.Neos.DeepLNodeTranslate'
    '@action': 'translateNodeAndTheirChildrenByIdentifier'
    '@format': 'json'
