Neos:
  Flow:
    mvc:
      routes:
        'SteinbauerIT.Neos.DeepLNodeTranslate': true
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'SteinbauerIT.Neos.DeepLNodeTranslate:Commands':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'SteinbauerIT\Neos\DeepLNodeTranslate\Controller\Api\.*'
  Neos:
    modules:
      deepltranslate:
        label: 'DeepL Translate'
        controller: '\Neos\Neos\Controller\Module\ManagementController'
        description: 'DeepL Translate backend module'
        icon: 'fas fa-language'
        resource: 'Neos_Neos_Backend_Module_Management'
        submodules:
          order:
            label: 'Translation'
            controller: '\SteinbauerIT\Neos\DeepLNodeTranslate\Controller\Module\DeepLController'
            description: 'Translate Neos nodetype text with DeepL'
            icon: 'fas fa-language'
            actions:
              index:
                label: 'Translations'
                title: 'Translate Neos nodetype text'
            additionalResources:
              styleSheets:
                - 'resource://Neos.Twitter.Bootstrap/Public/3.3/css/bootstrap.min.css'
#    Ui:
#      resources:
##        stylesheets:
##          'SteinbauerIT.Neos.DeepLNodeTranslate':
##            resource: '${"resource://SteinbauerIT.Neos.DeepLNodeTranslate/Public/Plugin.css"}'
#        javascript:
#          'SteinbauerIT.Neos.DeepLNodeTranslate':
#            resource: '${"resource://SteinbauerIT.Neos.DeepLNodeTranslate/Public/Plugin.js"}'
#      frontendConfiguration:
#        'SteinbauerIT.Neos.DeepLNodeTranslate:Role': '${Security.hasRole("Neos.Neos:Administrator") ? true : false}'
#        'SteinbauerIT.Neos.DeepLNodeTranslate:NodeTypes': '${Configuration.setting("SteinbauerIT.Neos.DeepLNodeTranslate.nodeTypes")}'
#        'SteinbauerIT.Neos.DeepLNodeTranslate:Dimensions': '${Configuration.setting("Neos.ContentRepository.contentDimensions")}'

#SteinbauerIT:
#  Neos:
#    DeepLNodeTranslate:
#      authKey: 'your-auth-key'
#      nodeTypes:
#        'Neos.NodeTypes:Headline':
#          label: Headline
#          properties:
#            - title
#        'Neos.NodeTypes:Text':
#          label: Text
#          properties:
#            - text
#      prefer:
#        en: 'en-GB'
